import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';

import 'package:flutter/foundation.dart';

import '../transport/ble_log.dart';
import 'final_unlock_port.dart';
import 'real_packet_builder.dart' show FirmwareCommand;

/// Inputs for the FINAL 32-byte firmware unlock packet (Phase 32).
///
/// Every Collect must supply **this order's** boxes, transaction, and times.
/// MCU code and token sequence are generated by [FinalUnlockPacketBuilder]
/// unless injected for tests.
class FinalUnlockPacketRequest {
  const FinalUnlockPacketRequest({
    required this.boxNumbers,
    required this.transactionId,
    required this.startTimeUnixSeconds,
    required this.endTimeUnixSeconds,
    this.command = FirmwareCommand.open,
    this.orderId = '',
  });

  /// Firmware OPEN command (default [FirmwareCommand.open] = 0x01).
  final int command;

  /// Physical boxes on **this** order only (1–32).
  final List<int> boxNumbers;

  /// Transaction ID for this Collect / payment / order flow (ASCII).
  final String transactionId;

  /// Unlock window start — Unix seconds (existing app convention).
  final int startTimeUnixSeconds;

  /// Unlock / collection expiry — Unix seconds.
  final int endTimeUnixSeconds;

  /// Optional order id for debug logs only (not placed in the packet).
  final String orderId;
}

/// FINAL 32-byte firmware unlock packet builder (Phase 32).
///
/// Layout:
/// ```
/// Byte[0]       Command (Collect: always 0x01 OPEN)
/// Bytes[1..4]   Port (box bitmap from CURRENT ORDER, LE)
/// Bytes[5..8]   Transaction ID placeholder (4 random bytes)
/// Bytes[9..10]  MCU Code placeholder (2 random bytes)
/// Bytes[11..14] Start Time placeholder (4 random bytes)
/// Bytes[15..18] End Time placeholder (4 random bytes)
/// Byte[19]      Token Sequence placeholder (1 random byte)
/// Bytes[20..31] Reserved (0x00)
/// ```
///
/// Protocol-critical for Collect now: Command + Port only.
/// Placeholder fields are isolated and replaceable later.
class FinalUnlockPacketBuilder {
  FinalUnlockPacketBuilder({
    Random? random,
    Uint8List Function()? mcuCodeFactory,
    int Function()? tokenSequenceFactory,
  })  : _random = random ?? Random.secure(),
        _mcuCodeFactory = mcuCodeFactory,
        _tokenSequenceFactory = tokenSequenceFactory;

  final Random _random;
  final Uint8List Function()? _mcuCodeFactory;
  final int Function()? _tokenSequenceFactory;

  static const int packetLength = 32;

  static const int _commandOffset = 0;
  static const int _portOffset = 1;
  static const int _portLen = 4;
  static const int _txOffset = 5;
  static const int _txLen = 4;
  static const int _mcuOffset = 9;
  static const int _mcuLen = 2;
  static const int _startOffset = 11;
  static const int _endOffset = 15;
  static const int _timeLen = 4;
  static const int _tokenOffset = 19;
  // Reserved bytes 20–31 filled with 0x00 via Uint8List allocation.

  /// Timestamp helper retained for tests / future professor encoding.
  static const Endian timestampEndian = Endian.big;

  /// Production Collect packet.
  ///
  /// Only [boxNumbers] (current order) drive Port. Command is always 0x01.
  /// All other non-reserved fields are fresh random placeholders.
  Uint8List buildCollect({
    required List<int> boxNumbers,
    String orderId = '',
  }) {
    _validateBoxes(boxNumbers);

    final packet = Uint8List(packetLength);
    final boxes = List<int>.from(boxNumbers);
    final mask = FinalUnlockPort.buildPortMask(boxes);
    final portBytes = FinalUnlockPort.encodePort32(mask);
    final txPlaceholder = _randomBytes(_txLen);
    final mcu = buildMcuCode();
    final startPlaceholder = _randomBytes(_timeLen);
    final endPlaceholder = _randomBytes(_timeLen);
    final token = buildTokenSequenceCounter();

    packet[_commandOffset] = FirmwareCommand.open; // 0x01 — never random
    packet.setRange(_portOffset, _portOffset + _portLen, portBytes);
    packet.setRange(_txOffset, _txOffset + _txLen, txPlaceholder);
    packet.setRange(_mcuOffset, _mcuOffset + _mcuLen, mcu);
    packet.setRange(_startOffset, _startOffset + _timeLen, startPlaceholder);
    packet.setRange(_endOffset, _endOffset + _timeLen, endPlaceholder);
    packet[_tokenOffset] = token & 0xff;
    // Bytes 20–31 reserved = 0x00 from allocation.

    assert(packet.length == packetLength);
    assert(packet[0] == FirmwareCommand.open);

    if (kDebugMode) {
      _logPacket(
        packet,
        orderId: orderId,
        boxes: boxes,
        mask: mask,
        portBytes: portBytes,
        transactionId: 'placeholder(${_hex(txPlaceholder)})',
        mcu: mcu,
        startLabel: 'placeholder(${_hex(startPlaceholder)})',
        endLabel: 'placeholder(${_hex(endPlaceholder)})',
        token: token,
      );
    }

    return Uint8List.fromList(packet);
  }

  /// Structured build (unit tests / future non-placeholder fields).
  Uint8List build(FinalUnlockPacketRequest request) {
    _validate(request);

    final packet = Uint8List(packetLength);

    final boxes = List<int>.from(request.boxNumbers);
    final mask = FinalUnlockPort.buildPortMask(boxes);
    final portBytes = FinalUnlockPort.encodePort32(mask);
    final txBytes = _encodeTransactionIdAscii4(request.transactionId);
    final mcu = buildMcuCode();
    final token = buildTokenSequenceCounter();
    final startBytes =
        encodeTimestamp32(request.startTimeUnixSeconds);
    final endBytes = encodeTimestamp32(request.endTimeUnixSeconds);

    packet[_commandOffset] = request.command & 0xff;
    packet.setRange(_portOffset, _portOffset + _portLen, portBytes);
    packet.setRange(_txOffset, _txOffset + _txLen, txBytes);
    packet.setRange(_mcuOffset, _mcuOffset + _mcuLen, mcu);
    packet.setRange(_startOffset, _startOffset + _timeLen, startBytes);
    packet.setRange(_endOffset, _endOffset + _timeLen, endBytes);
    packet[_tokenOffset] = token & 0xff;

    assert(packet.length == packetLength);

    if (kDebugMode) {
      _logPacket(
        packet,
        orderId: request.orderId,
        boxes: boxes,
        mask: mask,
        portBytes: portBytes,
        transactionId: request.transactionId,
        mcu: mcu,
        startLabel: '${request.startTimeUnixSeconds}',
        endLabel: '${request.endTimeUnixSeconds}',
        token: token,
      );
    }

    return Uint8List.fromList(packet);
  }

  /// Isolated MCU Code helper — exactly 2 random bytes until professor value.
  Uint8List buildMcuCode() {
    final custom = _mcuCodeFactory;
    if (custom != null) {
      final bytes = custom();
      if (bytes.length != _mcuLen) {
        throw ArgumentError('MCU Code must be exactly $_mcuLen bytes');
      }
      return Uint8List.fromList(bytes);
    }
    return _randomBytes(_mcuLen);
  }

  /// Isolated Token Sequence Counter — random u8 until professor rules.
  int buildTokenSequenceCounter() {
    final custom = _tokenSequenceFactory;
    if (custom != null) {
      final v = custom();
      if (v < 0 || v > 255) {
        throw ArgumentError('Token Sequence Counter must be 0–255');
      }
      return v;
    }
    return _random.nextInt(256);
  }

  /// Encode Unix-seconds timestamp to exactly 4 bytes (tests / future use).
  static Uint8List encodeTimestamp32(int unixSeconds) {
    if (unixSeconds < 0 || unixSeconds > 0xFFFFFFFF) {
      throw ArgumentError(
        'timestamp $unixSeconds out of u32 range',
      );
    }
    final out = Uint8List(_timeLen);
    ByteData.sublistView(out).setUint32(
      0,
      unixSeconds & 0xFFFFFFFF,
      timestampEndian,
    );
    return out;
  }

  Uint8List _randomBytes(int length) {
    final out = Uint8List(length);
    for (var i = 0; i < length; i++) {
      out[i] = _random.nextInt(256);
    }
    return out;
  }

  static void _validateBoxes(List<int> boxNumbers) {
    if (boxNumbers.isEmpty) {
      throw ArgumentError('boxNumbers must not be empty');
    }
    for (final b in boxNumbers) {
      if (b < FinalUnlockPort.minBox || b > FinalUnlockPort.maxBox) {
        throw ArgumentError(
          'boxNumber $b out of range '
          '(${FinalUnlockPort.minBox}–${FinalUnlockPort.maxBox})',
        );
      }
    }
  }

  static void _validate(FinalUnlockPacketRequest request) {
    if (request.command < 0 || request.command > 255) {
      throw ArgumentError('command out of u8 range: ${request.command}');
    }
    _validateBoxes(request.boxNumbers);
    if (request.transactionId.trim().isEmpty) {
      throw ArgumentError('transactionId must not be empty');
    }
    if (request.startTimeUnixSeconds < 0 ||
        request.startTimeUnixSeconds > 0xFFFFFFFF) {
      throw ArgumentError('startTime out of u32 range');
    }
    if (request.endTimeUnixSeconds < 0 ||
        request.endTimeUnixSeconds > 0xFFFFFFFF) {
      throw ArgumentError('endTime out of u32 range');
    }
  }

  /// 4-byte ASCII field for structured [build] tests only.
  static Uint8List _encodeTransactionIdAscii4(String value) {
    final encoded = utf8.encode(value.trim());
    for (final b in encoded) {
      if (b > 0x7F) {
        throw ArgumentError(
          'transactionId must be ASCII for 4-byte firmware field',
        );
      }
    }
    if (encoded.length > _txLen) {
      throw ArgumentError(
        'transactionId ASCII length ${encoded.length} exceeds $_txLen bytes '
        '(FINAL packet has no silent truncation)',
      );
    }
    final out = Uint8List(_txLen);
    for (var i = 0; i < encoded.length; i++) {
      out[i] = encoded[i];
    }
    return out;
  }

  static String _hex(Uint8List bytes) =>
      bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join(' ');

  static void _logPacket(
    Uint8List packet, {
    required String orderId,
    required List<int> boxes,
    required int mask,
    required Uint8List portBytes,
    required String transactionId,
    required Uint8List mcu,
    required String startLabel,
    required String endLabel,
    required int token,
  }) {
    BleLog.d('── FINAL UNLOCK PACKET (32 bytes) ─────────────');
    if (orderId.isNotEmpty) BleLog.d('ORDER: $orderId');
    BleLog.d('BOXES: $boxes');
    BleLog.d('PORT MASK: ${FinalUnlockPort.maskHex(mask)}');
    BleLog.d('PORT: ${FinalUnlockPort.encodedHex(portBytes)}');
    BleLog.d('Transaction ID: $transactionId');
    BleLog.d(
      'MCU Code: ${mcu.map((b) => b.toRadixString(16).padLeft(2, '0')).join(' ')}',
    );
    BleLog.d('Start Time: $startLabel');
    BleLog.d('End Time: $endLabel');
    BleLog.d('Token Sequence: $token');
    BleLog.d('Packet length: ${packet.length}');
    BleLog.d(
      'PACKET: ${packet.map((b) => b.toRadixString(16).padLeft(2, '0')).join(' ')}',
    );
    BleLog.d('──────────────────────────────────────────────');
  }
}

